---
# tasks file for deploy
- name: verificando o container que esta no ar
  stat:
   path: /etc/nginx/sites-enabled/green.conf
  register: vhost

- name: copiando a index do green
  copy:
   src: /var/lib/jenkins/workspace/bluegreen-deploy/
   dest: /var/lib/docker/volumes/green/_data/
  when: vhost.stat.exists == False

- name: copiando a index do blue
  copy:
   src: /var/lib/jenkins/workspace/bluegreen-deploy/
   dest: /var/lib/docker/volumes/blue/_data/
  when: vhost.stat.exists == True

- name: pegando ip do container green
  shell: "docker exec green hostname -I"
  when: vhost.stat.exists == False
  register: ipgreen

- name: pegando ip do container blue
  shell: "docker exec blue hostname -I"
  when: vhost.stat.exists == True
  register: ipblue

- name: Criando vhost green
  template:
    src: templates/vhost_green
    dest: /etc/nginx/sites-enabled/green.conf
  when: vhost.stat.exists == False

- name: Criando vhost blue
  template:
    src: templates/vhost_blue
    dest: /etc/nginx/sites-enabled/blue.conf
  when: vhost.stat.exists == True

- name: apagando vhost green
  file:
   path: /etc/nginx/sites-enabled/green.conf
   state: absent
  when: vhost.stat.exists == True

- name: apagando vhost blue
  file:
   path: /etc/nginx/sites-enabled/blue.conf
   state: absent
  when: vhost.stat.exists == False

- name: realizando reload do nginx
  service:
   name: nginx
   state: reloaded
