- name: Quarta playbook
  hosts: all
  tasks:
   - name: testando se um arquivo existe
     shell: " [ -f /etc/profile.d/dexter ] "
     register: result
     ignore_errors: yes
   
   - name: configurando uma variavel do sistema
     shell: echo "export DEXTER=/opt/dexter > /etc/profile.d/dexter"
     when: result.rc == 0
