- name: Remover Apache
  hosts: all
  tasks:
   - name: remover do debian
     apt:
      name: apache2
      state: absent
     when: ansible_os_family == "Debian"

   - name: remover do centos
     yum:
      name: httpd
      state: absent
     when: ansible_os_family == "RedHat"
