---
# tasks file for prereqs
- name: garantindo pacotes basicos
  package:
   name: 
    - docker-ce
    - nginx
    - python-pip

- name: instalando o docker-py
  pip:
   name: docker-py

- name: garantindo os servicos rodando
  service:
   name: "{{item}}"
   state: started
  with_items:
   - nginx
   - docker
