---

- name: Minha primeira playbook
  hosts: all
  vars:
   - username: sysadmin
  tasks:
   - name: Adicionando usuario
     user:
      name: "{{username}}"
      state: present

   - name: Instalando programas
     package:
      name: 
       - vim
       - cowsay
       - sl
       - figlet
      state: present
      update_cache: yes
     ignore_errors: yes
