#!/bin/bash

# Set up any specific permissions needed...
 chmod '0644' '/etc/apt/sources.list.d/puppet5.list'
 chmod '0644' '/etc/apt/trusted.gpg.d/puppet5-keyring.gpg'

# Run postinstall scripts on install if defined
if [ $1 = configure ] && [ -z $2 ] ; then
 : no postinstall scripts provided
fi

# Run postinstall scripts on upgrade if defined
if [ $1 = configure ] && [ -n $2 ] ; then
 : no postinstall scripts provided
fi
