#!/bin/bash

# Run post-removal scripts on upgrade if defined
if [ $1 = upgrade ] && [ -n $2 ] ; then
 : no postremove scripts provided
fi

# Run post-removal scripts on removal if defined
if [ $1 = remove ] && [ -z $2 ] ; then
 : no postremove scripts provided
fi

 # switch based on systemd vs systemv
 #
systemctl daemon-reload >/dev/null 2>&1 || :
 # switch based on systemd vs systemv
 #
systemctl daemon-reload >/dev/null 2>&1 || :
 # switch based on systemd vs systemv
 #
systemctl daemon-reload >/dev/null 2>&1 || :
