- name: Instalando apache2 em Debian
  package:
   name: "{{apache_debian}}"
   state: present
  when: ansible_os_family == "Debian"

- name: Instalando apache2 em Centos
  package:
   name: "{{apache_centos}}"
   state: present
  notify:
   - start apache centos
   - disable firewalld
  when: ansible_os_family == "RedHat"
