- name: Instalando pacotes
  apt:
   name: "{{item}}"
   state: present
  with_items:
   - apache2

- name: Configurando site
  copy:
   src: files/index.html 
   dest: /var/www/html/index.html
   owner: www-data
   group: www-data
   mode: 0644

